apiVersion: v1
kind: Pod
metadata:
  name: f21ao-site
  labels:
    app: web
spec:
  containers:
    - name: f21ao
      image: abrar/f21ao
      imagePullPolicy: Never
      ports:
        - containerPort: 8088
